// Generated by Dagger (https://dagger.dev).
package com.coderio.pocmvvmandroid.main.products.controller;

import com.coderio.pocmvvmandroid.main.products.repository.ProductsRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ProductsController_Factory implements Factory<ProductsController> {
  private final Provider<ProductsRepository> productsRepositoryProvider;

  public ProductsController_Factory(Provider<ProductsRepository> productsRepositoryProvider) {
    this.productsRepositoryProvider = productsRepositoryProvider;
  }

  @Override
  public ProductsController get() {
    return newInstance(productsRepositoryProvider.get());
  }

  public static ProductsController_Factory create(
      Provider<ProductsRepository> productsRepositoryProvider) {
    return new ProductsController_Factory(productsRepositoryProvider);
  }

  public static ProductsController newInstance(ProductsRepository productsRepository) {
    return new ProductsController(productsRepository);
  }
}
